@ServiceXpert.Api.Presentation_HostAddress = https://localhost:7023

POST {{ServiceXpert.Api.Presentation_HostAddress}}/api/issues
Content-Type: application/json

{
  "name": "This is a title",
  "description": "This is a description"
}

###

GET {{ServiceXpert.Api.Presentation_HostAddress}}/api/issues/SXP-1
Accept: application/json

###

GET {{ServiceXpert.Api.Presentation_HostAddress}}/api/issues
Accept: application/json

###

GET {{ServiceXpert.Api.Presentation_HostAddress}}/api/issues?status=open
Accept: application/json

###

DELETE {{ServiceXpert.Api.Presentation_HostAddress}}/api/issues/SXP-1

###

PATCH {{ServiceXpert.Api.Presentation_HostAddress}}/api/issues/SXP-1
Content-Type: application/json

[
  {
    "op": "replace",
    "path": "/issueStatusID",
    "value": "3"
  },
  {
    "op": "replace",
    "path": "/issuePriorityID",
    "value": "3"
  }
]

###