@ServiceXpert.API.Presentation_HostAddress = https://localhost:7023

POST {{ServiceXpert.API.Presentation_HostAddress}}/api/issue
Content-Type: application/json

{
  "name": "Test"
}

###

GET {{ServiceXpert.API.Presentation_HostAddress}}/api/issue/SXP-1
Accept: application/json

###

GET {{ServiceXpert.API.Presentation_HostAddress}}/api/issue
Accept: application/json

###

DELETE {{ServiceXpert.API.Presentation_HostAddress}}/api/issue/SXP-1

###

PATCH {{ServiceXpert.API.Presentation_HostAddress}}/api/issue/SXP-1
Content-Type: application/json

[
  {
    "op": "replace",
    "path": "/issueStatusID",
    "value": "3"
  },
  {
    "op": "replace",
    "path": "/issuePriorityID",
    "value": "3"
  }
]

###